### PR TITLE
Proposal 1: `did:new`

### PR DESCRIPTION
**Pull request by brianorwhatever**
This is a first pass at attempting to specify an approach similar to what is stated in #11.

### CODE REVIEW

**Comment by swcurran** [comment]
@brianorwhatever — first comment — can you update the PR to include DCO - Developer Certificate of Origin - https://github.com/apps/dco?  We use it for all commits in everything we do, so that we can push the code (if needed) to Hyperledger and other open source repositories.

**Comment by swcurran** [comment]
@brianorwhatever — first comment — can you update the PR to include DCO - Developer Certificate of Origin - https://github.com/apps/dco?  We use it for all commits in everything we do, so that we can push the code (if needed) to Hyperledger and other open source repositories.

**Comment by brianorwhatever** [comment]
@swcurran yep done, thanks for the link that was easy

**Comment by brianorwhatever** [comment]
Ideas from this have been worked into #18

**Pull request closed without merging**
